/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AppControllerGetHello$Params } from './fn/app/app-controller-get-hello';
export { appControllerGetHello } from './fn/app/app-controller-get-hello';
